# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 139a32a741c6d4afdb1f6696786495b065e14cbc4952a3c1d6d9ff8e9a801a5c2994265cb72d554656d1c0d480d4c417a6e029fa3bcdc6431d6bf15727a334ac

test:
  secret_key_base: 0bb0ea877abc6739addb76213332e4c72ef7054482a505065e5e1d6c20fac2de354db3eb21ef6181b0bbc1e93f044b2b8367aa1826b497f27b672d4093b136bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
